/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:2a51564d-802e-4e42-b479-11cecf648152",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_MjQ02dBjf",
    "aws_user_pools_web_client_id": "7ds1ugih9qdqil1pqoqho5fseb",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-west-2",
            "maps": {
                "items": {
                    "map2c22066f-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "map2c22066f-dev"
            }
        }
    }
};


export default awsmobile;
